version: 2
updates:
  - package-ecosystem: github-actions
    open-pull-requests-limit: 100
    directory: /
    schedule:
      time: "08:00"
      timezone: "America/Los_Angeles"
      interval: weekly
    allow:
      - dependency-type: all
    groups:
      all:
        patterns:
          - "*"
    reviewers:
      - lingrino

  - package-ecosystem: gomod
    open-pull-requests-limit: 100
    directory: /
    schedule:
      time: "08:00"
      timezone: "America/Los_Angeles"
      interval: weekly
    allow:
      - dependency-type: all
    groups:
      all:
        patterns:
          - "*"
    reviewers:
      - lingrino
