linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-blank: true
  gocognit:
    min-complexity: 10
  goconst:
    min-occurrences: 2
  gocyclo:
    min-complexity: 10
  golint:
    min-confidence: 0
  nakedret:
    max-func-lines: 0

issues:
  exclude-rules:
    - text: "G404:" # Ignore weak random number generator lint. We do not need strong randomness here.
      linters:
        - gosec
    - path: _test.go
      linters:
        - dupl # many functions in tests look like duplicates
        - funlen # test function can be very long due to test cases
    - path: (example|benchmark)_.*test.go
      linters:
        - errcheck # not required to check errors in examples/benchmarks
        - ineffassign # not required to check errors in examples/benchmarks
